"""empty message

Revision ID: 1b0b42c5ac6e
Revises: 
Create Date: 2023-08-11 09:08:19.372733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0b42c5ac6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('source', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('prohibited_domains',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('domain', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prohibited_domains')
    op.drop_table('links')
    # ### end Alembic commands ###
